import 'package:flutter/material.dart';
import 'new_receipt_screen.dart';
class DashboardScreen extends StatelessWidget {
  const DashboardScreen({super.key});

    Widget buildCard(
          BuildContext context,
                IconData icon,
                      String title,
                            Color color,
                              ) {
                                  return Card(
                                        elevation: 4,
                                              child: InkWell(
                                                      onTap: () {
                                                              Navigator.push(
                                                                  context,
                                                                      MaterialPageRoute(
                                                                            builder: (_) => const NewReceiptScreen(),
                                                                                ),
                                                                                  );
                                                                                  },
                                                      }
                                                              child: Container(
                                                                        padding: const EdgeInsets.all(20),
                                                                                  child: Column(
                                                                                              mainAxisAlignment: MainAxisAlignment.center,
                                                                                                          children: [
                                                                                                                        Icon(icon, size: 50, color: color),
                                                                                                                                      const SizedBox(height: 15),
                                                                                                                                                    Text(
                                                                                                                                                                    title,
                                                                                                                                                                                    textAlign: TextAlign.center,
                                                                                                                                                                                                    style: const TextStyle(
                                                                                                                                                                                                                      fontSize: 16,
                                                                                                                                                                                                                                        fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                  @override
                                                                                                                                                                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                        return Scaffold(
                                                                                                                                                                                                                                                                                                                              appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                      title: const Text("Huduma Receipt Pro"),
                                                                                                                                                                                                                                                                                                                                              centerTitle: true,
                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                          body: Padding(
                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                          child: GridView.count(
                                                                                                                                                                                                                                                                                                                                                                                    crossAxisCount: 2,
                                                                                                                                                                                                                                                                                                                                                                                              crossAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                                                                                                                        mainAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                                                                                                                                                              buildCard(context, Icons.receipt_long, "New Receipt", Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                          buildCard(context, Icons.people, "Customers", Colors.blue),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      buildCard(context, Icons.inventory, "Services", Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  buildCard(context, Icons.history, "Receipt History", Colors.orange),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              buildCard(context, Icons.bar_chart, "Reports", Colors.purple),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          buildCard(context, Icons.settings, "Settings", Colors.grey),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }