import 'package:flutter/material.dart';

class NewReceiptScreen extends StatefulWidget {
  const NewReceiptScreen({super.key});

    @override
      State<NewReceiptScreen> createState() => _NewReceiptScreenState();
      }

      class _NewReceiptScreenState extends State<NewReceiptScreen> {

        final customerController = TextEditingController();
          final serviceController = TextEditingController();
            final amountController = TextEditingController();
              final paidController = TextEditingController();
                final notesController = TextEditingController();

                  @override
                    Widget build(BuildContext context) {
                        return Scaffold(
                              appBar: AppBar(
                                      title: const Text("New Receipt"),
                                            ),
                                                  body: SingleChildScrollView(
                                                          padding: const EdgeInsets.all(16),
                                                                  child: Column(
                                                                            children: [

                                                                                        TextField(
                                                                                                      controller: customerController,
                                                                                                                    decoration: const InputDecoration(
                                                                                                                                    labelText: "Customer Name",
                                                                                                                                                    border: OutlineInputBorder(),
                                                                                                                                                                  ),
                                                                                                                                                                              ),

                                                                                                                                                                                          const SizedBox(height: 15),

                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                    controller: serviceController,
                                                                                                                                                                                                                                  decoration: const InputDecoration(
                                                                                                                                                                                                                                                  labelText: "Service",
                                                                                                                                                                                                                                                                  border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                        const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                                                    TextField(
                                                                                                                                                                                                                                                                                                                                  controller: amountController,
                                                                                                                                                                                                                                                                                                                                                keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                              decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                              labelText: "Amount",
                                                                                                                                                                                                                                                                                                                                                                                              border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                        ),

                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              controller: paidController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          labelText: "Amount Paid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          controller: notesController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        maxLines: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      labelText: "Notes",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 25),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SnackBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content: Text("Receipt Saved Successfully")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: const Text("Generate Receipt"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }